[package]
name = "veil"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
aes = "0.8"
cbc = "0.1"
block-padding = "0.2"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
rand = { version = "0.8", features = ["std"] }
